In [1]:
import tensorflow as tf

In [6]:
image_batch = tf.constant([
    [
        [[0, 255, 0], [0, 255, 0], [0, 255, 0]],
        [[0, 255, 0], [0, 255, 0], [0, 255, 0]]
    ],
    [
        [[0, 255, 0], [0, 255, 0], [0, 255, 0]],
        [[0, 255, 0], [0, 255, 0], [0, 255, 0]]
    ]
])

#image_batch.get_shape()
with tf.Session() as sess:
    print(sess.run(image_batch)[0][0][0])

[  0 255   0]


In [10]:
input_batch = tf.constant([
    [
        [[0.0], [1.0]],
        [[2.0], [3.0]]
    ],
    [
        [[2.0], [3.0]],
        [[4.0], [5.0]]
    ]
])

kernel = tf.constant([
    [
        [[1.0, 2.0]]
    ]
])

#input_batch.get_shape()
#kernel.get_shape()

conv2d = tf.nn.conv2d(input_batch, kernel, strides=[1, 1, 1, 1], padding='SAME')
with tf.Session() as sess:
    print(sess.run(conv2d))

[[[[  0.   0.]
   [  1.   2.]]

  [[  2.   4.]
   [  3.   6.]]]


 [[[  2.   4.]
   [  3.   6.]]

  [[  4.   8.]
   [  5.  10.]]]]
